# Generated by Django 3.2 on 2021-04-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_direction', models.CharField(max_length=200, verbose_name='Название направления')),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculties', models.CharField(max_length=200, verbose_name='Название факультета')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.directions', verbose_name='Направление подготовки')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_group', models.CharField(max_length=200, verbose_name='Название группы')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.faculties', verbose_name='Факультет')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_subject', models.CharField(max_length=200, verbose_name='Название дисциплины')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.directions', verbose_name='Направление')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.group', verbose_name='Группа')),
            ],
        ),
    ]
