# Generated by Django 3.2 on 2021-04-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directions',
            options={'verbose_name': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='faculties',
            options={'verbose_name': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Дисциплины'},
        ),
        migrations.AlterModelTable(
            name='directions',
            table='direction',
        ),
        migrations.AlterModelTable(
            name='faculties',
            table='faculty',
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AlterModelTable(
            name='subjects',
            table='subject',
        ),
    ]
