# Generated by Django 3.2 on 2021-04-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210413_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directions',
            options={'verbose_name': 'Направления', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='faculties',
            options={'verbose_name': 'Факультеты', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группы', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студенты', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Дисциплины', 'verbose_name_plural': 'Дисциплины'},
        ),
    ]
